# Generated by Django 3.2.3 on 2022-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSITUweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
